### ISSUE TITLE
request for full dataset

### ISSUE THREAD

**Issue by seifer08ms** [hrlblab/SimTriplet#2]
Thanks for sharing the great research. By the way, could you kindly share the full dataset since the paper have been already published online (https://link.springer.com/chapter/10.1007%2F978-3-030-87196-3). Thanks a lot.

**Comment by hrlblab** [comment]
The journal version is under review. We plan to release the data after the journal version is accepted. Please feel free to email the contact author for the questions of data augmentation and implementation. Thanks.
