### ISSUE TITLE
Nice Paper, but unfortunately incomplete implementation

### ISSUE THREAD

**Issue by FabianHoerst** [hrlblab/SimTriplet#3]
Seems like a good paper, but results can't be reproduced or transferred to a new dataset since the implementation is incomplete. Some data augmentations are missing. Furthermore, the implementation does not match with the figures of the model provided in the paper.

**Comment by hrlblab** [comment]
The journal version is under review. We plan to release the data after the journal version is accepted. Please feel free to email the contact author for the questions of data augmentation and implementation. Thanks.
